# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
title = "CAE EDEM Support"
version = "1.0.0"  # Semantic Versioning is used: https://semver.org/
description = "Kit-CAE Extension to add support for EDEM datasets."
category = "internal"  # How to categorize this in the Extension Manager
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"  # Icon to show in the Extension Manager
keywords = ["kit", "cae", "edem"]  # Search keywords for the Extension Manager
readme  = "docs/README.md"  # Path (relative to the root) or content of readme markdown file for UI

[dependencies]
"omni.cae.data" = {}
"omni.kit.tool.asset_importer" = {}
"omni.client" = {}
"omni.cae.pipapi" = {}

[settings]

[[python.module]]
name = "omni.cae.edem"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]


[[test]]
dependencies = [
]

args = [
]
